<?php if ($block->isPopupEnabled()) : ?>
<script type="text/javascript" bronto-popup-id="<?php echo implode(' ', $block->escapeHtml($block->getPopupDomains())); ?>" src="https://cdn.bronto.com/popup/delivery.js"></script>
<script type="text/javascript">
  if (document.addEventListener) {
    document.addEventListener('bronto:popup-submitted', function(e) {
      jQuery.post('<?php echo $block->escapeHtml($block->getPopupUrl()); ?>', {
        emailAddress: e.detail.email
      });
    }, false);
  }
</script>
<?php endif; ?>
